### ISSUE TITLE
Horizontal scroll bars

### ISSUE THREAD

**Issue by wellhairy** [kentcc/kentgov#22]
There are horizontal scroll bars on Live but not locally, there also seems to be inconsistent extra white space. This issue might be limited to the democracy site. https://democracy.kent.gov.uk/uuCoverPage.aspx?bcr=1

**Comment by LidorLapid** [comment]
This is being caused by the following element: `<textarea tabindex="-1" style="position: absolute;top: -999px;left: 0px;right: auto;bottom: auto;border: 0px;box-sizing: content-box;word-wrap: break-word;overflow: hidden;height: 0px !important;min-height: 0px !important;"></textarea>`

It looks like box-sizing: content-box is causing it to take up space in the flow of the document despite the fact it's positioned absolutely.
